version: "3"

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_DATABASE=megaanticheat-dev
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
